//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class reporte_formas
    {
        public string NombreUsuario { get; set; }
        public string Tipo_forma { get; set; }
        public string Nombre_forma { get; set; }
        public int Resultado { get; set; }
        public decimal cal { get; set; }
    }
}
